# docker-compose.yml
services:
  mongodb:
    image: mongo:latest
    container_name: irrigation-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./Server
    ports:
      - "5000:5000"
    env_file:
      - ./Server/.env
    environment:
      HOST: 127.0.0.1
      PORT: 5000
      MONGO_URI: mongodb://localhost:27017/iot_app
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - mongodb
      - redis
      - mqtt

  frontend:
    build:
      context: ./mobile_app
    ports:
      - "4200:80"

  mqtt:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
    command: mosquitto -c /mosquitto/config/mosquitto.conf

volumes:
  mongo_data: