name: mobile_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  intl: ^0.20.2
  shared_preferences: ^2.3.0
  socket_io_client: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
